import 'package:flutter/material.dart';

/// Colors from the Stitch "Playful Youth Fintech" design system
/// (Tailwind sky / slate / emerald scales used by the screens).
abstract final class AppColors {
  static const surface = Color(0xFFF8FAFF);

  // Material 3 tokens generated by Stitch for the design system.
  static const dsPrimary = Color(0xFF006591);
  static const dsPrimaryContainer = Color(0xFF0EA5E9);
  static const dsSurface = Color(0xFFFAF8FF);
  static const dsSurfaceContainerLow = Color(0xFFF2F3FF);
  static const dsSurfaceContainerHigh = Color(0xFFE2E7FF);
  static const dsOnSurface = Color(0xFF131B2E);
  static const dsOnSurfaceVariant = Color(0xFF3E4850);
  static const dsOutlineVariant = Color(0xFFBEC8D2);

  static const sky50 = Color(0xFFF0F9FF);
  static const sky100 = Color(0xFFE0F2FE);
  static const sky200 = Color(0xFFBAE6FD);
  static const sky400 = Color(0xFF38BDF8);
  static const sky500 = Color(0xFF0EA5E9);
  static const sky600 = Color(0xFF0284C7);
  static const sky700 = Color(0xFF0369A1);
  static const sky800 = Color(0xFF075985);

  static const slate50 = Color(0xFFF8FAFC);
  static const slate100 = Color(0xFFF1F5F9);
  static const slate200 = Color(0xFFE2E8F0);
  static const slate300 = Color(0xFFCBD5E1);
  static const slate400 = Color(0xFF94A3B8);
  static const slate500 = Color(0xFF64748B);
  static const slate600 = Color(0xFF475569);
  static const slate700 = Color(0xFF334155);
  static const slate800 = Color(0xFF1E293B);

  static const indigo100 = Color(0xFFE0E7FF);

  static const emerald50 = Color(0xFFECFDF5);
  static const emerald100 = Color(0xFFD1FAE5);
  static const emerald200 = Color(0xFFA7F3D0);
  static const emerald400 = Color(0xFF34D399);
  static const emerald500 = Color(0xFF10B981);
  static const emerald600 = Color(0xFF059669);
  static const emerald800 = Color(0xFF065F46);
  static const emerald950 = Color(0xFF022C22);

  static const amber50 = Color(0xFFFFFBEB);
  static const amber100 = Color(0xFFFEF3C7);
  static const amber200 = Color(0xFFFDE68A);
  static const amber400 = Color(0xFFFBBF24);
  static const amber500 = Color(0xFFF59E0B);
  static const amber600 = Color(0xFFD97706);
  static const amber700 = Color(0xFFB45309);
  static const amber800 = Color(0xFF92400E);

  static const orange50 = Color(0xFFFFF7ED);

  static const rose50 = Color(0xFFFFF1F2);
  static const rose100 = Color(0xFFFFE4E6);
  static const rose400 = Color(0xFFFB7185);
  static const rose500 = Color(0xFFF43F5E);
  static const rose600 = Color(0xFFE11D48);

  static const indigo50 = Color(0xFFEEF2FF);
  static const indigo500 = Color(0xFF6366F1);
  static const violet50 = Color(0xFFF5F3FF);
  static const violet100 = Color(0xFFEDE9FE);
  static const violet500 = Color(0xFF8B5CF6);
  static const pink50 = Color(0xFFFDF2F8);
  static const pink100 = Color(0xFFFCE7F3);
  static const pink400 = Color(0xFFF472B6);
  static const pink500 = Color(0xFFEC4899);
  static const slate900 = Color(0xFF0F172A);
  static const sky300 = Color(0xFF7DD3FC);
  static const sky900 = Color(0xFF0C4A6E);
  static const emerald300 = Color(0xFF6EE7B7);
  static const emerald700 = Color(0xFF047857);
}

/// Motion tokens. Material 3 "emphasized" easing starts slowly and settles
/// over a long tail, which reads as smoother than [Curves.easeOutCubic] for
/// anything moving a meaningful distance; the accelerate pair is its
/// counterpart for exits.
const appEmphasizedDecelerate = Cubic(0.05, 0.7, 0.1, 1);
const appEmphasizedAccelerate = Cubic(0.3, 0, 0.8, 0.15);

/// Comfortaa ships as a variable font, so weight is applied through the
/// `wght` axis as well as [FontWeight] to render correctly on every platform.
TextStyle comfortaa({
  required double size,
  FontWeight weight = FontWeight.w400,
  Color color = AppColors.slate800,
  double? height,
  double? letterSpacing,
}) {
  return TextStyle(
    fontFamily: 'Comfortaa',
    fontSize: size,
    fontWeight: weight,
    fontVariations: [FontVariation.weight(weight.value.toDouble())],
    color: color,
    height: height,
    letterSpacing: letterSpacing,
  );
}

ThemeData buildAppTheme() {
  return ThemeData(
    useMaterial3: true,
    fontFamily: 'Comfortaa',
    scaffoldBackgroundColor: AppColors.surface,
    colorScheme: ColorScheme.fromSeed(
      seedColor: AppColors.sky500,
      primary: AppColors.sky600,
      surface: AppColors.surface,
    ),
  );
}
