import 'package:flutter/material.dart';

/// The app color themes a kid can pick in "Өнгөний тохиргоо".
enum AppThemeChoice { blue, pink }

/// The accent scale a theme swaps in for the `sky*` and primary `ds*` tokens.
class AppPalette {
  const AppPalette({
    required this.c50,
    required this.c100,
    required this.c200,
    required this.c300,
    required this.c400,
    required this.c500,
    required this.c600,
    required this.c700,
    required this.c800,
    required this.c900,
    required this.dsPrimary,
    required this.pageBackground,
    required this.pageBackgroundMuted,
  });

  final Color c50, c100, c200, c300, c400, c500, c600, c700, c800, c900;
  final Color dsPrimary;

  /// Tinted page backgrounds behind the white cards: the default one and the
  /// greyer one used by Profile.
  final Color pageBackground;
  final Color pageBackgroundMuted;

  /// Tailwind sky: the original Stitch design.
  static const blue = AppPalette(
    c50: Color(0xFFF0F9FF),
    c100: Color(0xFFE0F2FE),
    c200: Color(0xFFBAE6FD),
    c300: Color(0xFF7DD3FC),
    c400: Color(0xFF38BDF8),
    c500: Color(0xFF0EA5E9),
    c600: Color(0xFF0284C7),
    c700: Color(0xFF0369A1),
    c800: Color(0xFF075985),
    c900: Color(0xFF0C4A6E),
    dsPrimary: Color(0xFF006591),
    pageBackground: Color(0xFFF5F8FE),
    pageBackgroundMuted: Color(0xFFF4F6FB),
  );

  /// Tailwind pink, kept apart from the rose used for errors.
  static const pink = AppPalette(
    c50: Color(0xFFFDF2F8),
    c100: Color(0xFFFCE7F3),
    c200: Color(0xFFFBCFE8),
    c300: Color(0xFFF9A8D4),
    c400: Color(0xFFF472B6),
    c500: Color(0xFFEC4899),
    c600: Color(0xFFDB2777),
    c700: Color(0xFFBE185D),
    c800: Color(0xFF9D174D),
    c900: Color(0xFF831843),
    dsPrimary: Color(0xFFA3195B),
    pageBackground: Color(0xFFFEF6FA),
    pageBackgroundMuted: Color(0xFFFBF5F8),
  );

  static AppPalette of(AppThemeChoice choice) => switch (choice) {
    AppThemeChoice.blue => blue,
    AppThemeChoice.pink => pink,
  };
}

/// The active color theme. `ArdKidsApp` rebuilds the whole tree when it
/// changes, so every `AppColors.sky*` read picks up the new palette.
final appThemeChoice = ValueNotifier(AppThemeChoice.blue);

/// Colors from the Stitch "Playful Youth Fintech" design system
/// (Tailwind sky / slate / emerald scales used by the screens).
///
/// `sky*`, `dsPrimary`, `dsPrimaryContainer` and the `pageBackground*`
/// tints are the theme accent: they
/// follow [appThemeChoice], so they are getters and can't be used in `const`
/// expressions. Everything else is a fixed constant.
abstract final class AppColors {
  static AppPalette get _p => AppPalette.of(appThemeChoice.value);

  static const surface = Color(0xFFF8FAFF);

  // Material 3 tokens generated by Stitch for the design system.
  static Color get dsPrimary => _p.dsPrimary;
  static Color get dsPrimaryContainer => _p.c500;
  static const dsSurface = Color(0xFFFAF8FF);
  static const dsSurfaceContainerLow = Color(0xFFF2F3FF);
  static const dsSurfaceContainerHigh = Color(0xFFE2E7FF);
  static const dsOnSurface = Color(0xFF131B2E);
  static const dsOnSurfaceVariant = Color(0xFF3E4850);
  static const dsOutlineVariant = Color(0xFFBEC8D2);

  static Color get pageBackground => _p.pageBackground;
  static Color get pageBackgroundMuted => _p.pageBackgroundMuted;

  static Color get sky50 => _p.c50;
  static Color get sky100 => _p.c100;
  static Color get sky200 => _p.c200;
  static Color get sky300 => _p.c300;
  static Color get sky400 => _p.c400;
  static Color get sky500 => _p.c500;
  static Color get sky600 => _p.c600;
  static Color get sky700 => _p.c700;
  static Color get sky800 => _p.c800;
  static Color get sky900 => _p.c900;

  static const slate50 = Color(0xFFF8FAFC);
  static const slate100 = Color(0xFFF1F5F9);
  static const slate200 = Color(0xFFE2E8F0);
  static const slate300 = Color(0xFFCBD5E1);
  static const slate400 = Color(0xFF94A3B8);
  static const slate500 = Color(0xFF64748B);
  static const slate600 = Color(0xFF475569);
  static const slate700 = Color(0xFF334155);
  static const slate800 = Color(0xFF1E293B);

  static const indigo100 = Color(0xFFE0E7FF);

  static const emerald50 = Color(0xFFECFDF5);
  static const emerald100 = Color(0xFFD1FAE5);
  static const emerald200 = Color(0xFFA7F3D0);
  static const emerald400 = Color(0xFF34D399);
  static const emerald500 = Color(0xFF10B981);
  static const emerald600 = Color(0xFF059669);
  static const emerald800 = Color(0xFF065F46);
  static const emerald950 = Color(0xFF022C22);

  static const amber50 = Color(0xFFFFFBEB);
  static const amber100 = Color(0xFFFEF3C7);
  static const amber200 = Color(0xFFFDE68A);
  static const amber400 = Color(0xFFFBBF24);
  static const amber500 = Color(0xFFF59E0B);
  static const amber600 = Color(0xFFD97706);
  static const amber700 = Color(0xFFB45309);
  static const amber800 = Color(0xFF92400E);

  static const orange50 = Color(0xFFFFF7ED);

  static const rose50 = Color(0xFFFFF1F2);
  static const rose100 = Color(0xFFFFE4E6);
  static const rose400 = Color(0xFFFB7185);
  static const rose500 = Color(0xFFF43F5E);
  static const rose600 = Color(0xFFE11D48);

  static const indigo50 = Color(0xFFEEF2FF);
  static const indigo500 = Color(0xFF6366F1);
  static const violet50 = Color(0xFFF5F3FF);
  static const violet100 = Color(0xFFEDE9FE);
  static const violet500 = Color(0xFF8B5CF6);
  static const pink50 = Color(0xFFFDF2F8);
  static const pink100 = Color(0xFFFCE7F3);
  static const pink400 = Color(0xFFF472B6);
  static const pink500 = Color(0xFFEC4899);
  static const slate900 = Color(0xFF0F172A);
  static const emerald300 = Color(0xFF6EE7B7);
  static const emerald700 = Color(0xFF047857);
}

/// Motion tokens. Material 3 "emphasized" easing starts slowly and settles
/// over a long tail, which reads as smoother than [Curves.easeOutCubic] for
/// anything moving a meaningful distance; the accelerate pair is its
/// counterpart for exits.
const appEmphasizedDecelerate = Cubic(0.05, 0.7, 0.1, 1);
const appEmphasizedAccelerate = Cubic(0.3, 0, 0.8, 0.15);

/// Inter ships as a variable font, so weight is applied through the `wght`
/// axis as well as [FontWeight] to render correctly on every platform. Its
/// `opsz` axis (14–32) follows the font size, so small labels get the open
/// text cut and balances the tighter display cut.
TextStyle inter({
  required double size,
  FontWeight weight = FontWeight.w400,
  Color color = AppColors.slate800,
  double? height,
  double? letterSpacing,
}) {
  return TextStyle(
    fontFamily: 'Inter',
    fontSize: size,
    fontWeight: weight,
    fontVariations: [
      FontVariation.weight(weight.value.toDouble()),
      FontVariation.opticalSize(size.clamp(14, 32).toDouble()),
    ],
    color: color,
    height: height,
    letterSpacing: letterSpacing,
  );
}

ThemeData buildAppTheme() {
  return ThemeData(
    useMaterial3: true,
    fontFamily: 'Inter',
    scaffoldBackgroundColor: AppColors.surface,
    colorScheme: ColorScheme.fromSeed(
      seedColor: AppColors.sky500,
      primary: AppColors.sky600,
      surface: AppColors.surface,
    ),
    // Sheets span the full width on iPad too, like the pages, instead of
    // Material's 640 cap.
    bottomSheetTheme: const BottomSheetThemeData(constraints: BoxConstraints()),
  );
}
